project:
  type: website

website:
  title: "Michelle Evans"
  site-url: https://mvevans.netlify.app
  navbar:
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "Academic Pubs"
        href: pubs.qmd
      - text: "CV"
        href: CV.qmd
      - icon: github
        href: https://github.com/mvevans89
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/mv-evans.bsky.social
format:
  html:
    theme: minty
    css: styles.css



